### ISSUE TITLE
Einbindung einer freien JS Chart Bibliothek (MIT)

### ISSUE THREAD

**Issue by dergel** [yakamara/dashboard#2]
um diverse Charts und Darstellung visuell einfach rüberbringen zu klnnen

**Comment by xong** [comment]
Muss es JS sein oder geht auch eine reine CSS-Lösung?

https://chartscss.org

**Comment by dergel** [comment]
wie gerade besprochen. lieber das hier: https://www.chartjs.org/

und direkt eine Klasse bauen, mit der man das als Widget verwenden kann. Es geht hier dann vor allem um einfache Charts. D.h. Erstmal einfacher Balkenchart/Linechat/Doughnut ohne speziellen extra Kurven.
