### ISSUE TITLE
Sortierung der Widgets überdenken

### ISSUE THREAD

**Issue by dergel** [yakamara/dashboard#8]
Macht das Verschieben der Widgets so Sinn ? Die Widgets sortieren sich ja immer wieder neu ein, je nach Browsergröße .. Wenn ich etwas verschiebe, erschliesst sich mir nicht, wir sich das insgesamr aufbaut. Was könnten wir machen ?

**Comment by iceman-fx** [comment]
Die sortierte Reihenfolge müsste immer korrekt gesetzt werden, so dass es bei entsprechend großem Bildschirm immer gleich bleibt.
